'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const ndarray = require('ndarray')
const ops = require('../ndarray-ops.js')

test('upstream README and 114-assertion fixture behavior', () => {
  const x = ndarray(new Float64Array(10))
  const y = ndarray(new Float64Array(10))
  assert.equal(ops.equals(x, y), true)
  y.set(2, 1)
  assert.equal(ops.equals(x, y), false)
  ops.assigns(y, 5)
  for (let i = 0; i < 10; ++i) assert.equal(y.get(i), 5)
  ops.add(x, y, y)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 10)
  ops.addeq(x, y)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 15)
  ops.adds(x, y, 1)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 6)
  ops.addseq(x, 2)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 8)
  ops.recip(x, y)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 0.2)
  ops.negeq(x)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), -0.2)
  const z = ndarray(new Uint8Array(10))
  ops.lt(z, x, y)
  for (let i = 0; i < 10; ++i) assert.ok(z.get(i))
  ops.assigns(x, 4)
  ops.sqrteq(x)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 2)
  ops.powops(x, y, 2)
  for (let i = 0; i < 10; ++i) assert.equal(x.get(i), 32)
  assert.equal(ops.any(z), true)
  assert.equal(ops.all(z), true)
  assert.equal(ops.sum(y), 50)
  assert.equal(ops.prod(y), 5 ** 10)
  assert.equal(ops.norm2squared(y), 250)
  assert.equal(ops.norm2(y), Math.sqrt(250))
  assert.equal(ops.norminf(y), 5)
  assert.equal(ops.norm1(y), 50)
  assert.equal(ops.sup(y), 5)
  assert.equal(ops.inf(y), 5)
  y.set(0, 10)
  y.set(1, -10)
  assert.deepEqual(ops.argmax(y), [0])
  assert.deepEqual(ops.argmin(y), [1])
})

test('rank-zero and empty identities', () => {
  const scalar = ndarray(new Float64Array([3]), [])
  assert.equal(ops.sum(scalar), 3)
  assert.equal(ops.assigns(scalar, 7), scalar)
  assert.equal(scalar.get(), 7)
  const empty = ndarray(new Float64Array(0), [0])
  assert.equal(ops.any(empty), false)
  assert.equal(ops.all(empty), true)
  assert.equal(ops.sum(empty), 0)
  assert.equal(ops.prod(empty), 1)
  assert.equal(ops.sup(empty), -Infinity)
  assert.equal(ops.inf(empty), Infinity)
  assert.deepEqual(ops.argmin(empty), [0])
})
